package:
  name: conda-self
  {% if GIT_DESCRIBE_TAG is defined and GIT_BUILD_STR is defined %}
  version: {{ GIT_DESCRIBE_TAG }}+{{ GIT_BUILD_STR }}
  {% else %}
  version: 0.0.0dev0
  {% endif %}

source:
  # git_url only captures committed code
  git_url: ../

build:
  number: 0
  noarch: python
  script:
    - python -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python 3.10
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
  run:
    - python >=3.10
    - conda >=26.1.1
    - importlib-metadata >=4.8.3  # [py<312]

test:
  requires:
    - python 3.10
  imports:
    - conda_self
  commands:
    - conda self --help

about:
  home: https://github.com/conda-incubator/conda-self
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A self command for conda
  dev_url: https://github.com/conda-incubator/conda-self
